[package]
name = "pipeline"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true

[dependencies]
# Telemetry dependencies
tracing-subscriber = "0.3.18"

# Workspace dependencies
kona-derive.workspace = true
tracing.workspace = true
