[package]
name = "zkvm-client"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# workspace
cfg-if.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
anyhow.workspace = true
lru.workspace = true
spin.workspace = true
async-trait.workspace = true
tracing.workspace = true

# local
kona-common = { path = "../../../crates/common", version = "0.0.1" }
kona-common-proc = { path = "../../../crates/common-proc", version = "0.0.1" }
kona-preimage = { path = "../../../crates/preimage", version = "0.0.1", features = ["serde"] }
kona-primitives = { path = "../../../crates/primitives", version = "0.0.1" }
kona-mpt = { path = "../../../crates/mpt", version = "0.0.1" }
kona-derive = { path = "../../../crates/derive", default-features = false, version = "0.0.1" }
kona-executor = { path = "../../../crates/executor", version = "0.0.1" }

tracing-subscriber = { version = "0.3.18", optional = true }
hashbrown = "0.14.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
sha256 = "1.5.0"

# sp1
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.0.5-testnet"  }

[dev-dependencies]

[features]
tracing-subscriber = ["dep:tracing-subscriber"]

[[bin]]
name = "kona"
path = "src/kona.rs"
