[package]
name = "zkvm-client"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# workspace
cfg-if.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
anyhow.workspace = true
lru.workspace = true
spin.workspace = true
async-trait.workspace = true
tracing.workspace = true

# local
kona-common = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-common-proc = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-preimage = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream", features = ["rkyv"] }
kona-primitives = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-mpt = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-derive = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream", default-features = false }
kona-executor = { git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
kona-client = {  git = "https://github.com/moongate-forks/kona/", branch = "kona-upstream" }
tracing-subscriber = { version = "0.3.18", optional = true }
hashbrown = "0.14.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2", default-features = false, features = ["compress"] }
bincode = "1.3.3"

# sp1
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.0.5-testnet"  }
hex = "0.4.3"

[dev-dependencies]

[features]
tracing-subscriber = ["dep:tracing-subscriber"]

# if we pull this crate out from kona, don't forget to add the tiny-keccak patch here
