name: Publish Trusted Sync Binary Image

on:
  workflow_dispatch:
    inputs:
      customTag:
        description: 'Custom Docker Image Tag (keep empty for latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository }}/trusted-sync
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate with container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Publish `trusted-sync`
        uses: docker/build-push-action@v6
        with:
          file: examples/trusted-sync/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/ethereum-optimism/kona/trusted-sync:${{ github.event.inputs.customTag }}
          labels: ${{ steps.meta.outputs.labels }}
