name: Build and Run zkvm_host

on:
  pull_request:
    branches:
      - zkvm

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download & install SP1
      run: |
        curl -L https://sp1.succinct.xyz | bash
        source /home/runner/.bashrc
        source ~/.bashrc
    - name: Push SP1 program
      run: pushd bin/programs/sp1
    - name: Compile the client program
      run: cargo prove build --ignore-rust-version
    - name: Pop
      run: popd
    - name: Run zkvm_host
      run: cargo run --manifest-path bin/zkvm_host/Cargo.toml --release
      timeout-minutes: 20
