name: Build and Run zkvm_host

on:
  pull_request:
    branches:
      - zkvm

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download sp1up
      run: |
        curl -L https://sp1.succinct.xyz | bash
        source ~/.bashrc
        sp1up
        source ~/.bashrc
        pushd bin/programs/sp1
        cargo prove build --ignore-rust-version
        popd
    - name: Run zkvm_host
      run: cargo run --manifest-path bin/zkvm_host/Cargo.toml --release
      timeout-minutes: 20
