name: Build and Run zkvm_host

on:
  pull_request:
    branches:
      - zkvm

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download sp1up
      uses: curl -L https://sp1.succinct.xyz | bash

    - name: Install SP1
      uses: sp1up

    # - name: Push SP1 program
    #   uses: pushd bin/programs/sp1

    # - name: Compile the client program
    #   uses: cargo prove build --ignore-rust-version

    # - name: Pop
    #   uses: popd

    # - name: Run zkvm_host
    #   run: cargo run --manifest-path bin/zkvm_host/Cargo.toml --release
    #   timeout-minutes: 20
